### ISSUE TITLE
allow mimetype "image" and "audio"

### ISSUE THREAD

**Issue by TimDaub** [neume-network/schema#20]
- music-os needs to know which manifestation to access 
https://github.com/neume-network/strategies/blob/b981f606db2cb8e15fdc67e1cebd0c3916ea06c2/src/strategies/soundxyz-get-tokenuri/transformer.mjs#L52

**Comment by TimDaub** [comment]
fixed by #19

**Comment by il3ven** [comment]
Closing issue since it has been fixed.
