### ISSUE TITLE
add an ipfs message extractor message that requires a valid CID

### ISSUE THREAD

**Issue by TimDaub** [neume-network/schema#35]
- cid checking can be done with this library: https://github.com/multiformats/js-multiformats

**Comment by il3ven** [comment]
Is the plan here to send IPFS URLs to extraction-worker so it could download content without the strategy needing to convert it to an IPFS gateway?

**Comment by TimDaub** [comment]
Maybe. I think the strategies themselves should not deal with having to figure out the formatting of an IPFS link. Ideally, a specialized library would either know what to do with any URI (e.g. within the extraction worker). Or as a separate npm package.
