### ISSUE TITLE
soundxyz manifestation audio link points to sound pinata gateway

### ISSUE THREAD

**Issue by TimDaub** [neume-network/schema#37]
from @reimertz 

```
Catalog:  ipfs://...
Sound:  https://soundxyz.mypinata.cloud/ipfs/...
Mint Songs: ipfs://...
```

if its an IPFS link, we should use the `ipfs://hash` formatting

**Comment by il3ven** [comment]
I agree that all IPFS links should use `ipfs://` irrespective of what the underlying NFT follows. I think we should also use `ipfs://` not only for audio manifestation links but for `erc721.tokenuri` too. @TimDaub What do you think? Should I introduce a function `anyIpfsUriToNativeIpfsUri`?

**Comment by TimDaub** [comment]
yeah but at this point IMO it may make sense building a separate npm package

**Comment by il3ven** [comment]
let me first add it as a part of strategies and if you feel it is worthy of a separate package we can just pick it out.

**Comment by TimDaub** [comment]
hi

**Comment by TimDaub** [comment]
ok sorry for close/reopen. it was a fatfinger

**Comment by il3ven** [comment]
Sound audio links will not point to pinata gateway after neume-network/strategies#312.

```js
manifestations: [
  {
    version,
    uri: ifIpfsConvertToNativeIpfs(datum.audio_url),
    mimetype: "audio",
  },
  {
    version,
    uri: ifIpfsConvertToNativeIpfs(datum.image),
    mimetype: "image",
  },
  {
    version,
    uri: ifIpfsConvertToNativeIpfs(datum.animation_url),
    mimetype: "image",
  },
```

> From: https://github.com/neume-network/strategies/blob/7b9bd619e52ae32703553883dc5990429b2b1f63/src/strategies/soundxyz-get-tokenuri/transformer.mjs#L49-L64
